---
title: "p8105_hw5_nl2835"
author: "Nancy Le"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)

```


```{r load csv file}
homicides <-
  read.csv("./local/homicide-data.csv") |> 
  janitor::clean_names() |> 
  separate(reported_date, into = c("year", "month", "day"), sep = c(4,6))  
```

The raw data describes victim name, race, age, sex, location of homicide, and whether an arrest was made.

```{r}
homicides = homicides |> 
  mutate(city_state = paste(city, state, sep = ", ")) |> 
  group_by(city_state) 

```

```{r count number of homicides}
homicides |> 
  summarize(count = n())
```

There are `r nrow(homicides)` homicides from 2010 to 2016.

```{r}
homicides |> 
  filter(disposition == "Closed without arrest" | disposition == "Open/No arrest") |> 
  summarize(count = n())
```

There are `r nrow(homicides |> filter(disposition == "Closed without arrest" | disposition == "Open/No arrest"))` unsolved homicides. 


```{r df unsolved}
baltimore = homicides |> 
  filter(city_state == "Baltimore, MD") |> 
  mutate(
    unresolved = as.numeric(disposition == "Closed without arrest" | disposition == "Open/No arrest")) |> 
  select(city_state, unresolved, everything()) |> 
  group_by(unresolved) |> 
  summarize(number = n()) |> 
  mutate(total = sum(number)) |> 
  filter(unresolved == 1) |> 
  select(number, total)
```

```{r prop test}
baltimore_pt = 
  prop.test(baltimore$number, baltimore$total) |>
  broom::tidy() |> 
  janitor::clean_names()

baltimore_pt |> 
  select(estimate, conf_low, conf_high) |> knitr::kable()
```

The estimated proportion of homicides unsolved is 0.6456 with a confidence interval of [0.627, 0.663].







